name: '🐛 Bug Report'
description: 'Please read through all instructions in the template below before submitting your issue to ensure that we have all the information needed to help.'
labels: ['bug']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an open or closed issue already exists for the bug you encountered. If a bug exists and it is closed as complete it may not yet be in a stable release.
    options:
    - label: I have searched for existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A brief, clear description of the issue you're encountering.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: What were you expecting to happen instead?
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Detailed steps to reproduce the behavior, if possible.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...

      If providing any docker compose/run commands, please use the code block format to ensure it is more readable.
      To format your code, use three backticks (```) before and after the code block.
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide details about your environment, including:
        - **Operating System** (e.g., Ubuntu 22.04, Windows 11)
        - **Plex Auto Languages Version** (e.g., 1.3.2)
        - **Plex Version** (e.g., 1.41.3.9314)
        - **Docker Install** (e.g., Yes or No)
        - **Other relevant information** (e.g., Provide Python version if running bare metal)
    value: |
        - OS:
        - Plex Auto Languages Version:
        - Plex Version:
        - Docker Install:
        - Other Information:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: |
      Please provide your full log related to this issue.
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Anything else that could help us investigate and resolve the issue (links, screenshots, etc.).
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
