name: '🚀 Feature Request'
description: 'Suggest an idea or improvement for Plex Auto Languages to help us enhance the experience.'
labels: ['enhancement']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an open or closed issue already exists for the feature you are requesting. If a feature request exists and it is closed as complete it may not yet be in a stable release.
    options:
    - label: I have searched for existing feature requests
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe
    description: Provide a clear and concise description of the problem you're facing that this feature would solve.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: What specific feature or functionality would you like to see implemented? Be as detailed as possible.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: If applicable, provide a brief overview of other solutions or features you've thought about or tried.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: |
      Any links, references, mockups, or other context that can help us understand and evaluate your feature request.
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
